### ISSUE TITLE
Please write the Documentation of Post FIx expression and binary conversion

### ISSUE THREAD

**Issue by JOnMila** [adasarpan404/stl-javascript#21]

**Comment by JOnMila** [comment]
I have been going through code. 
I have been found that You have implemented logic for postfix expressions and binary conversion.

**Comment by Jugger404Naut** [comment]
Can You write the code for this.

**Comment by Jugger404Naut** [comment]
sorry documentation

**Comment by adasarpan404** [comment]
#22 You have created this pull request

**Comment by adasarpan404** [comment]
Ok
